[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python -u src/bot.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/health"
port = 8080
interval = 300
timeout = 10
healthyThreshold = 2
unhealthyThreshold = 3
